package com.example.stockdroid.app.fragment;

import android.app.AlertDialog;
import android.app.ListFragment;
import android.content.Context;
import android.content.DialogInterface;
import android.content.SharedPreferences;
import android.content.res.Resources;
import android.os.Bundle;
import android.view.View;
import android.widget.AdapterView;
import android.widget.ArrayAdapter;
import android.widget.Button;
import android.widget.ListView;
import android.widget.TextView;

import com.example.stockdroid.app.R;
import com.example.stockdroid.app.activity.StockActivity;

import java.util.List;

/**
 * Created by tim on 5/21/14.
 */
public class PortfolioFragment extends ListFragment {

    private static final String TAG = "PortfolioFragment.java";
    private List<String> stocks;
    private ArrayAdapter<String> adapter;
    private Button addButton;


    private AdapterView.OnItemClickListener itemSelectedListener = new AdapterView.OnItemClickListener() {
        @Override
        public void onItemClick(AdapterView<?> parent, View view, int position, long id) {
            StockFragment fragment = (StockFragment) getActivity().getFragmentManager().findFragmentById(R.layout.fragment_stock);
            fragment.query(((TextView) view).getText().toString());
        }
    };


    // responds to events generated by long pressing ListView item
    private AdapterView.OnItemLongClickListener itemLongClickListener =
            new AdapterView.OnItemLongClickListener() {
                // called when a ListView item is long-pressed
                @Override
                public boolean onItemLongClick(AdapterView<?> listView, View view,
                                               int arg2, long arg3) {

                    final String symbol =
                            ((TextView) view).getText().toString();

                    // create a new AlertDialog
                    AlertDialog.Builder builder = new AlertDialog.Builder(getListView().getContext());

                    // set the AlertDialog's message
                    builder.setMessage("Are you sure you want to remove " + symbol + "?");

                    // set the AlertDialog's positive Button
                    builder.setPositiveButton("Yes",
                            new DialogInterface.OnClickListener() {
                                @Override
                                public void onClick(DialogInterface dialog, int id) {
                                    adapter.remove(symbol);
                                    SharedPreferences sharedPreferences =
                                            getActivity().getApplicationContext().getSharedPreferences(
                                                    StockActivity.SHARED_PREFERENCES_NAME,
                                                    Context.MODE_PRIVATE);

                                    SharedPreferences.Editor preferencesEditor = sharedPreferences.edit();
                                    preferencesEditor.remove(symbol);
                                    preferencesEditor.apply();
//                                    listChangeListener.onStockDeleted(symbol);
                                    adapter.notifyDataSetChanged();
                                }
                            }
                    );
                    builder.setNegativeButton("Cancel",
                            new DialogInterface.OnClickListener() {
                                public void onClick(DialogInterface dialog, int id) {
                                    dialog.cancel();
                                }
                            }
                    );

                    builder.create().show();
                    return true;
                }
            };

    /**
     * Default constructor.
     */
    public PortfolioFragment() {
        super();
    }

    @Override
    public void onActivityCreated(Bundle savedInstanceStateBundle) {
        super.onActivityCreated(savedInstanceStateBundle);

        // create ArrayList to save city names
        stocks = getArguments().getStringArrayList("stocks");
        System.out.println(stocks.size());

        // set the Fragment's ListView adapter
        adapter = new ArrayAdapter<>(getActivity().getApplicationContext(), R.layout.stock_item, stocks);
        setListAdapter(adapter);

        getListView().setChoiceMode(ListView.CHOICE_MODE_SINGLE);
        getListView().setOnItemLongClickListener(itemLongClickListener);
    }

}
